services:
  - type: web
    name: n8n
    env: docker
    image: n8nio/n8n:latest
    plan: free
    healthCheckPath: /healthz
    envVars:
      - key: N8N_PORT
        value: 8080
      - key: N8N_HOST
        value: 0.0.0.0
      - key: NODE_ENV
        value: production
